export const categoryData = [
  {
    id: "m0qyiz35p3wosbfnb8",
    title: "Personal",
  },
  {
    id: "m0qyk53pjuk5zhyh7m",
    title: "Work",
  },
  {
    id: "m0qykd70l2lyqeakdgm",
    title: "Shopping",
  },
  {
    id: "m0qykjup2lev8xlmqcy",
    title: "Health",
  },
  {
    id: "m0qykq2k9ekux15gixn",
    title: "Coding",
  },
  {
    id: "m0qyl2nujvnsk9mamd",
    title: "Fitness",
  },
];

export const tasksData = [
  {
    id: "id59d9ebd220d66",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Organize Your Digital Photos.",
    category: "Personal",
    completed: true,
  },
  {
    id: "id8f3b086547209",
    categoryId: "m0qyl2nujvnsk9mamd",
    task: "Run 500 meters",
    category: "Fitness",
    completed: false,
  },
  {
    id: "id20b9617fb545d",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Update Your Resume.",
    category: "Personal",
    completed: false,
  },
  {
    id: "id191781937a08b",
    categoryId: "m0qykjup2lev8xlmqcy",
    task: "Prepare Healthy Meals.",
    category: "Health",
    completed: false,
  },
  {
    id: "id358b17cad8f93",
    categoryId: "m0qyk53pjuk5zhyh7m",
    task: "Complete a Project Report.",
    category: "Work",
    completed: false,
  },
  {
    id: "id78372ce35876d",
    categoryId: "m0qykd70l2lyqeakdgm",
    task: "Make a Grocery List",
    category: "Shopping",
    completed: true,
  },
  {
    id: "idd4942cf3cde5c",
    categoryId: "m0qykd70l2lyqeakdgm",
    task: "Buy New Clothes.",
    category: "Shopping",
    completed: false,
  },
  {
    id: "id0f6e139876352",
    categoryId: "m0qykq2k9ekux15gixn",
    task: "Write Documentation.",
    category: "Coding",
    completed: false,
  },
  {
    id: "idf9213e24df8ad",
    categoryId: "m0qyl2nujvnsk9mamd",
    task: "Incorporate Strength Training.",
    category: "Fitness",
    completed: false,
  },
  {
    id: "idbe6502c7dc87e",
    categoryId: "m0qykjup2lev8xlmqcy",
    task: "sleep early",
    category: "Health",
    completed: false,
  },
  {
    id: "idcd8ff22444138",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Create a Budget.",
    category: "Personal",
    completed: false,
  },
  {
    id: "ide2310c095b1c",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Write in a Journal.",
    category: "Personal",
    completed: false,
  },
  {
    id: "idb961e07f4e602",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Declutter Your Home.",
    category: "Personal",
    completed: false,
  },
  {
    id: "id3c5cd6f42d29d",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Schedule a Check-Up.",
    category: "Personal",
    completed: false,
  },
  {
    id: "id2d243aeef0c22",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Plan a Weekend Trip.",
    category: "Personal",
    completed: false,
  },
  {
    id: "idb9a5c2f9727b3",
    categoryId: "m0qyiz35p3wosbfnb8",
    task: "Learn a New Skill or Hobby.",
    category: "Personal",
    completed: false,
  },
  {
    id: "id1e4a2c07b8c9",
    categoryId: "m0qyk53pjuk5zhyh7m",
    task: "Schedule a Team Meeting.",
    category: "Work",
    completed: false,
  },
  {
    id: "idb68a5c9f7e4d",
    categoryId: "m0qyk53pjuk5zhyh7m",
    task: "Review Your Work Goals.",
    category: "Work",
    completed: false,
  },
  {
    id: "idf1234ab56c9d",
    categoryId: "m0qyk53pjuk5zhyh7m",
    task: "Review Industry News.",
    category: "Work",
    completed: false,
  },
  {
    id: "id9a1e2c3d4f5a",
    categoryId: "m0qyk53pjuk5zhyh7m",
    task: "Optimize Your Workflow.",
    category: "Work",
    completed: false,
  },
  {
    id: "id7b9c8d6e5a4f",
    categoryId: "m0qykd70l2lyqeakdgm",
    task: "Get Birthday Gifts.",
    category: "Shopping",
    completed: false,
  },
  {
    id: "idef6789a0bc1",
    categoryId: "m0qykd70l2lyqeakdgm",
    task: "Find a New Book to Read.",
    category: "Shopping",
    completed: false,
  },
  {
    id: "id23a4b5c6d7e",
    categoryId: "m0qykd70l2lyqeakdgm",
    task: "Choose Home Décor.",
    category: "Shopping",
    completed: false,
  },
  {
    id: "id5f6e7a8b9c0d",
    categoryId: "m0qykd70l2lyqeakdgm",
    task: "Compare Prices Online.",
    category: "Shopping",
    completed: false,
  },
  {
    id: "id1b2c3d4e5f6a",
    categoryId: "m0qykjup2lev8xlmqcy",
    task: "Get Adequate Sleep.",
    category: "Health",
    completed: false,
  },
  {
    id: "id8a9b0c1d2e3f",
    categoryId: "m0qykjup2lev8xlmqcy",
    task: "Exercise Regularly.",
    category: "Health",
    completed: false,
  },
  {
    id: "id6f7e8a9b0c1d",
    categoryId: "m0qykq2k9ekux15gixn",
    task: "Fix Bugs in Your Code.",
    category: "Coding",
    completed: false,
  },
];
